services:
  propilkki2:
    build:
      context: ./propilkki2
      args:
        ORGA: "${ORGA}"
        SERVER_NAME: "${SERVER_NAME}"
        HOST_PW: "${HOST_PW}"
        ADMIN_PW: "${ADMIN_PW}"
        PILKKI_PW: "${PILKKI_PW}"
    container_name: propilkki2
    restart: unless-stopped
    env_file: .env
    ports:
      - 4500:4500
  mumble:
    image: "mumblevoip/mumble-server:latest"
    container_name: mumble
    restart: unless-stopped
    env_file: .env
    volumes:
      - mumble:/data
    ports:
      - 64738:64738
volumes:
  mumble:
